title: Sakshi Mukkirwar
logo: images/Githubprofile.jpeg
email: sakshimanish.mukkirwar@sjsu.edu
description: Data is the new fuel, and my curiosity drives me to explore different ideas and real-time problems revolving around the vast data pool
baseurl: "" # the subpath of your site, e.g., "/blog" if your site is hosted at "example.com/blog"
url: "" # the base hostname & protocol for your site, e.g., "http://example.com"

# Build settings
theme: jekyll-theme-minimal
markdown: kramdown

