title: Your site title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  This is a description of your site. You can use Markdown here to format it. This text will appear under your site title in the Cayman theme.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed

# Cayman theme specific
show_downloads: true
google_analytics: UA-XXXXX-Y # Replace with your Google Analytics tracking ID if you have one.
