title: Sakshi Mukkirwar
email: sakshimanish.mukkirwar@sjsu.edu
description: >- # this means to ignore newlines until "baseurl:"
  MS Data Analytics student at San Jose State University
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed

# Cayman theme specific
show_downloads: true
google_analytics: UA-XXXXX-Y # Replace with your Google Analytics tracking ID if you have one.
